language: python

python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8

install:
  # install deps
  - pip install -r requirements.txt
  - pip list

script:
  - pytest

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r reports/coverage.xml
