language: python

python:
    - 3.7
    - 3.8
    - 3.9

install:
  # temp fix for https://github.com/pypa/setuptools/issues/3293
  - pip install --upgrade importlib-metadata>=0.21
  # install deps
  - pip install -r requirements.txt
  - pip list

script:
  - pytest --cov-report xml:coverage.xml --cov-report term --cov=klimalogger tests

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
