language: python

python:
    - 3.3
    - 3.4
    - 3.5
    - 3.6

install:
  # install deps
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip list

script:
  - pytest

after_success:
  - coveralls
